### PR TITLE
Milestone 1

### PR DESCRIPTION
**Pull request by RyelBanfield**
This PR contains the project setup and deployment to Heroku.

### CODE REVIEW

**Review by afanimartin — CHANGES_REQUESTED** [review]
## Changes Required 🙏🏿 🙏🏿 🙏🏿 
Nice work on setting up the project. You managed to meet most of the requirements for this milestone.
### Highlights 🌵 🌵 🌵 
- app created using `create-react-app` command
- `redux`,`react-redux` and `prop-types` added to `package.json`

### Changes 🔕 🔕 🔕 
- your readme is not professional enough. you lack a section with instructions for contributing to this repo
- there is also no section for prerequisites. refer to this [template](https://github.com/microverseinc/readme-template) to make your readme more professional


### Martin Afani
#### Slack: whiz25

**Comment by RyelBanfield** [comment]
@afanimartin A readme was not requested for this milestone. It will be completed as the progress of the project goes on and will be finished before the final milestone.

**Review by afanimartin — APPROVED** [review]
## Approved 👍🏿 👍🏿 👍🏿 
Merge and proceed to the next milestone. Nice work.

### Martin Afani
#### Slack: whiz25

**Comment by RyelBanfield** [comment]
@afanimartin Thank you mate.

**Pull request merged**
